name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        which python
        conda install -c conda-forge git-annex
        pip install datalad
        pip install pytest flake8 pydocstyle
        pip install -e ./bids-validator
    - name: Check formatting
      shell: bash -l {0}
      run: |
        which python
        flake8 bids-validator/bids_validator
        pydocstyle bids-validator/bids_validator/bids_validator.py
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        which python
        pytest --doctest-modules bids-validator/bids_validator
